### ISSUE TITLE
感觉代码字体显示不友好

### ISSUE THREAD

**Issue by Mr-houzi** [bolnh/hexo-theme-material#599]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

## 问题描述

感觉代码字体不是原来的字体了，现在代码字体感觉显示不是特别友好，字体看的很难受，请问如何设置会原来的字体？

![问题截图](https://user-images.githubusercontent.com/26339918/35339191-e5f365bc-015a-11e8-8d33-3cddab215868.png)

**Comment by EIVX** [comment]
可以使用其他代码高亮插件

**Comment by jingyig01** [comment]
这个似乎是hexo自带的代码染色效果。你去主题下面开启prettify，效果会好一点。
