### ISSUE TITLE
文章菜单显示问题

### ISSUE THREAD

**Issue by hi-rustin** [bolnh/hexo-theme-material#661]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

当我完成一篇博客之后，侧边生成的菜单会出现有点击过的超链接样式，但是其他同级的菜单没有，是因为我的文章格式问题吗 ？这个菜单的解析是如何做的？是怎样的一个规则？
如图所示：
<img width="322" alt="qq20180517-210841 2x" src="https://user-images.githubusercontent.com/29879298/40179302-9670aabc-5a16-11e8-90fc-573a910bf4ae.png">
<img width="247" alt="qq20180517-210901 2x" src="https://user-images.githubusercontent.com/29879298/40179311-9d966a16-5a16-11e8-82e2-220647fba438.png">

**Comment by show-rosarugosa** [comment]
我用调试器看了下，是样式选择器的问题，不知道为什么有的菜单会不包含在<ol>标签中，导致丢失了.post-toc这个选择器样式
![image](https://user-images.githubusercontent.com/29879298/40180154-be06656a-5a18-11e8-9f44-1a712101748e.png)
<img width="721" alt="qq20180517-212432 2x" src="https://user-images.githubusercontent.com/29879298/40180199-d5a3511a-5a18-11e8-9d7f-2ace351ed3db.png">
原因是：
![image](https://user-images.githubusercontent.com/29879298/40180297-0e2fff24-5a19-11e8-9d2f-a1138f5822e1.png)
