### ISSUE TITLE
主题文档](https://material.viosey.com/)主题文档打不开,域名不能访问,有好心人可以发我一份吗

### ISSUE THREAD

**Issue by Dragon-super** [bolnh/hexo-theme-material#739]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

**Comment by AnonAlpha** [comment]
Here you are [material-theme-docs.netlify.com](material-theme-docs.netlify.com)

**Comment by blackyau** [comment]
https://neko-dev.github.io/material-theme-docs/#/

**Comment by TheInterestingSoul** [comment]
> Here you are [material-theme-docs.netlify.com](material-theme-docs.netlify.com)

Says `Not Found`

**Comment by TheInterestingSoul** [comment]
> https://neko-dev.github.io/material-theme-docs/#/

Says `Not Found`

**Comment by cubesky** [comment]
> > https://neko-dev.github.io/material-theme-docs/#/
> 
> Says `Not Found`

https://neko-dev.github.io/material-theme-docs/#/

**Comment by glazec** [comment]
https://github.com/glazec/hexo-theme-material.wiki.git
