### ISSUE TITLE
请问，这个主题如何指定文章的封面图片呢和放大博客文章中的图片？  

### ISSUE THREAD

**Issue by glennwu97** [bolnh/hexo-theme-material#743]
hexo-theme-material在新建的md文件首部中应该用什么关键字来指定文章封面的图片呢？此外，该如何修改站点配置文件来放大博客文章中的图片

**Comment by xiaoLit** [comment]
封面图      thumbnail:

放大可以用js的指定尺寸导入图片写法

**Comment by glennwu97** [comment]
好的 已解决问题，感谢！
