### ISSUE TITLE
分页栏乱码，如何解决？ How to solve my error in pagination display?

### ISSUE THREAD

**Issue by glennw97** [bolnh/hexo-theme-material#744]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

1.我想解决博客底部分页栏显示乱码的问题。
2.我想知道如何自定义博客底部的社交按钮,比如加一个微信链接。
1.I want to konow how to solve my error in pagination display?
2. I want to know how to DIY a new social link icon at the bottom of my blog.
![](https://gitee.com//gleenwu/picbed01/raw/master/img/20200331222742.jpg)
![](https://gitee.com//gleenwu/picbed01/raw/master/img/20200331222741.jpg)

**Comment by widsnoy** [comment]
将hexo降级到3.9.0试试，我也遇到了同样的问题，通过降级解决了。

**Comment by glennw97** [comment]
已解决，原因是从 Hexo 4 开始，这个分页功能（https://hexo.io/zh-cn/docs/helpers#paginator）会默认把 HTML 转义，要手动关掉 escape 才行。操作为: index.ejs, paginator类下 加入 escape: false。

**Comment by widsnoy** [comment]
> 已解决，原因是从 Hexo 4 开始，这个分页功能（[https://hexo.io/zh-cn/docs/helpers#paginator）会默认把](https://hexo.io/zh-cn/docs/helpers#paginator%EF%BC%89%E4%BC%9A%E9%BB%98%E8%AE%A4%E6%8A%8A) HTML 转义，要手动关掉 escape 才行。操作为: index.ejs, paginator类下 加入 escape: false。

谢谢，能不能麻烦帮我看看这个[问题](https://github.com/bolnh/hexo-theme-material/issues/745)
