### ISSUE TITLE
如何将我的博客文章页面向右边扩展？How to extend my post page to more right place with the left unchanged?

### ISSUE THREAD

**Issue by glennwu97** [bolnh/hexo-theme-material#747]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

如何将我的博客文章页面向右边扩展？我想让文章页面变得饱满一些，右边不用空出那么多的内容，请问我该如何修改主题的CSS或其他文件。 I want to utilize more space of my post page , therefore I want to ask how can I extend my post page to more right place by modifying css or other related files in this theme?

**Comment by Staroon** [comment]
- 修改文章显示宽度，max-width值调大即可，style.css和style.min.css均需要修改：
https://github.com/bolnh/hexo-theme-material/blob/d93c5a82db38d851dcb89961a42ef1ca09a9d677/source/css/style.css#L507
- 修改文章卡片圆角弧度，border-radius值调大即可，style.css和style.min.css均需要修改：
https://github.com/bolnh/hexo-theme-material/blob/d93c5a82db38d851dcb89961a42ef1ca09a9d677/source/css/style.css#L526

**Comment by Staroon** [comment]
> * 修改文章显示宽度，max-width值调大即可，style.css和style.min.css均需要修改：
>   https://github.com/bolnh/hexo-theme-material/blob/d93c5a82db38d851dcb89961a42ef1ca09a9d677/source/css/style.css#L507
> * 修改文章卡片圆角弧度，border-radius值调大即可，style.css和style.min.css均需要修改：
>   https://github.com/bolnh/hexo-theme-material/blob/d93c5a82db38d851dcb89961a42ef1ca09a9d677/source/css/style.css#L526
调整后点显示效果可参[我的博客](https://www.staroon.dev/)

**Comment by glennwu97** [comment]
问题已解决，很感谢!  我的博客地址是blog.glennwu.info有空欢迎来逛逛。
